# Generated by Django 4.2.7 on 2023-11-08 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.person')),
                ('last_service_date', models.DateField()),
                ('birthday', models.DateField(blank=True, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('credit_used', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('credit_available', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('credit_status', models.CharField(blank=True, max_length=30, null=True)),
                ('credit_status_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
            bases=('people.person',),
        ),
    ]
