# Generated by Django 4.2.7 on 2023-11-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_person_created_by_alter_person_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Employee'), (2, 'Customer'), (3, 'Vendor'), (4, 'Other')], null=True),
        ),
    ]
