# Generated by Django 4.2.7 on 2023-11-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_alter_person_person_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_service_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
