# Generated by Django 4.2.7 on 2023-11-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_last_reading_mileage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='model',
            name='vehicle_type',
            field=models.IntegerField(choices=[(1, 'Car'), (2, 'Motorbike'), (3, 'Truck'), (4, 'Van'), (5, 'Bus'), (6, 'Motorcycle'), (7, 'Trailer'), (8, 'Miscellaneous')], default=1),
            preserve_default=False,
        ),
    ]
