# Generated by Django 4.2.7 on 2023-11-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_remove_vehicle_vehicle_type_model_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='vehicle_type',
            field=models.IntegerField(choices=[(1, 'Car'), (2, 'SUV'), (3, 'Pickup'), (4, 'Truck'), (5, 'Van'), (6, 'Bus'), (7, 'Motorcycle'), (8, 'Trailer')]),
        ),
    ]
