# Generated by Django 4.2.7 on 2023-11-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_model_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.IntegerField(choices=[(1, 'Black'), (2, 'White'), (3, 'Red'), (4, 'Green'), (5, 'Blue'), (6, 'Yellow'), (7, 'Orange'), (8, 'Purple'), (9, 'Gray'), (10, 'Brown'), (11, 'Pink'), (12, 'Gold'), (13, 'Silver'), (14, 'Cyan'), (15, 'Magenta'), (16, 'Lime'), (17, 'Maroon'), (18, 'Navy'), (19, 'Olive'), (20, 'Teal'), (21, 'Violet'), (22, 'Rose'), (23, 'Crimson'), (24, 'Tan'), (25, 'Turquoise')]),
        ),
    ]
