# Generated by Django 4.2.7 on 2023-11-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_alter_vehicle_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='is_primary',
            field=models.BooleanField(default=True),
        ),
    ]
